### ISSUE TITLE
无法启动服务器

### ISSUE THREAD

**Issue by SulfuricM** [baka-gourd/LogUnSpam#3]
所用核心 Arclight 1.16.5

[16:08:02] [main/WARN] [forge/ForgeConfigSpec]: Configuration file /workspace/config/log_un_spam-common.toml is not correct. Correcting
[16:08:02] [main/WARN] [forge/ForgeConfigSpec]: Incorrect key general was corrected from null to its default, SimpleCommentedConfig:{}. 
[16:08:02] [main/WARN] [forge/ForgeConfigSpec]: Incorrect key general.commonFilterWords was corrected from null to its default, []. 
[16:08:02] [main/WARN] [forge/ForgeConfigSpec]: Incorrect key general.regexpFilterWords was corrected from null to its default, []. 
[16:08:02] [main/WARN] [forge/ForgeConfigSpec]: Incorrect key general.classFilterWords was corrected from null to its default, []. 
[16:08:02] [Thread-3/ERROR] [forge/FMLModContainer]: Exception caught during firing event: null
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: class com.nullpinter.logUnSpam.util.ConfigHandler onModConfigEvent(Lnet/minecraftforge/fml/config/ModConfig$ModConfigEvent;)V
java.lang.UnsupportedOperationException
        at java.base/java.util.Collections$1.remove(Unknown Source)
        at java.base/java.util.AbstractCollection.remove(Unknown Source)
        at com.nullpinter.logUnSpam.util.ConfigHandler.bakeConfig(ConfigHandler.java:46)
        at com.nullpinter.logUnSpam.util.ConfigHandler.onModConfigEvent(ConfigHandler.java:54)
        at net.minecraftforge.eventbus.ASMEventHandler_37_ConfigHandler_onModConfigEvent_ModConfigEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:138)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:138)
        at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:76)
        at net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:147)
        at com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

[16:08:02] [main/ERROR] [forge/FMLModContainer]: Exception caught during firing event: null
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: class com.nullpinter.logUnSpam.util.ConfigHandler onModConfigEvent(Lnet/minecraftforge/fml/config/ModConfig$ModConfigEvent;)V
java.lang.UnsupportedOperationException
        at java.base/java.util.Collections$1.remove(Unknown Source)
        at java.base/java.util.AbstractCollection.remove(Unknown Source)
        at com.nullpinter.logUnSpam.util.ConfigHandler.bakeConfig(ConfigHandler.java:46)
        at com.nullpinter.logUnSpam.util.ConfigHandler.onModConfigEvent(ConfigHandler.java:54)
        at net.minecraftforge.eventbus.ASMEventHandler_37_ConfigHandler_onModConfigEvent_ModConfigEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:138)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:138)
        at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:76)
        at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:92)
        at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:69)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at java.base/java.util.Collections$SynchronizedCollection.forEach(Unknown Source)
        at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:69)
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:195)
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:31)
        at net.minecraft.server.Main.main(MainMixin.java:95)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:43)
        at io.izzel.arclight.common.ArclightMain.run(ArclightMain.java:50)
        at io.izzel.arclight.server.Main_Forge.main(Main_Forge.java:16)
        at io.izzel.arclight.server.Launcher.main(Launcher.java:16)

java.lang.UnsupportedOperationException
        at java.base/java.util.Collections$1.remove(Unknown Source)
        at java.base/java.util.AbstractCollection.remove(Unknown Source)
        at com.nullpinter.logUnSpam.util.ConfigHandler.bakeConfig(ConfigHandler.java:46)
        at com.nullpinter.logUnSpam.util.ConfigHandler.onModConfigEvent(ConfigHandler.java:54)
        at net.minecraftforge.eventbus.ASMEventHandler_37_ConfigHandler_onModConfigEvent_ModConfigEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:138)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:138)
        at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:76)
        at net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:147)
        at com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
[16:08:03] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
java.lang.UnsupportedOperationException: null
        at java.util.Collections$1.remove(Unknown Source) ~[?:?] {}
        at java.util.AbstractCollection.remove(Unknown Source) ~[?:?] {}
        at com.nullpinter.logUnSpam.util.ConfigHandler.bakeConfig(ConfigHandler.java:46) ~[log_un_spam:1.0] {re:classloading}
        at com.nullpinter.logUnSpam.util.ConfigHandler.onModConfigEvent(ConfigHandler.java:54) ~[log_un_spam:1.0] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_37_ConfigHandler_onModConfigEvent_ModConfigEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:138) ~[forge:?] {re:classloading}
        at java.util.Optional.ifPresent(Unknown Source) ~[?:?] {}
        at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:138) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:76) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:92) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:69) ~[forge:?] {re:classloading}
        at java.lang.Iterable.forEach(Unknown Source) ~[?:?] {}
        at java.util.Collections$SynchronizedCollection.forEach(Unknown Source) ~[?:?] {}
        at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:69) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:195) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:31) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(MainMixin.java:95) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49) [forge-1.16.5-36.2.39.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46) [forge-1.16.5-36.2.39.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [forge-1.16.5-36.2.39.jar:?] {}
        at io.izzel.arclight.common.ArclightMain.run(ArclightMain.java:50) [arclight.jar:arclight-1.16.5-1.0.25-SNAPSHOT-509cb953] {}
        at io.izzel.arclight.server.Main_Forge.main(Main_Forge.java:16) [arclight.jar:arclight-1.16.5-1.0.25-SNAPSHOT-509cb953] {}
        at io.izzel.arclight.server.Launcher.main(Launcher.java:16) [arclight.jar:arclight-1.16.5-1.0.25-SNAPSHOT-509cb953] {}

**Comment by baka-gourd** [comment]
https://www.curseforge.com/minecraft/mc-mods/logunspam/files/4386484
